CLASS LHC_ZMERP_R_PURCHASEORDERITM DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZmerpRPurchaseorderitm
        RESULT result.
ENDCLASS.

CLASS LHC_ZMERP_R_PURCHASEORDERITM IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
